# 服务器相关配置
server:
  port: 8081
  tomcat:
    threads.max: 50
    max-connections: 100
    max-http-form-post-size: 120MB
    connection-timeout: 60000

# spring配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/poetize?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root