# 服务器相关配置
server:
  port: 8081
  tomcat:
    threads.max: 50
    max-connections: 100
    max-http-form-post-size: 120MB
    connection-timeout: 60000

# spring配置
spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3307/poetize?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  # 文件上传配置
  servlet:
    # 文件上传配置
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  # 邮件配置
  mail:
    host: smtp.qq.com
    username:
    password:
    default-encoding: utf-8
    protocol: smtp
    port: 465
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          ssl:
            enable: true

# mybatis-plus配置
mybatis-plus:
  # 配置mapper.xml文件位置
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    # sql语句日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 逻辑删除
      logic-delete-value: 1
      logic-not-delete-value: 0